### ISSUE TITLE
-Sourcedir should accept a path with more than 10 characters

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#10]
PS E:\labbuildr> Set-LABSources -Sourcedir "D:\Lab\labbuildr_sources"
Set-LABSources : Cannot validate argument on parameter 'Sourcedir'. The character length of the 24 argument is too long.
the character length of the argument so it is fewer than or equal to "10" characters, and then try the command again.
At line:1 char:27
- Set-LABSources -Sourcedir "D:\Lab\labbuildr_sources"
-                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Set-LABSources], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationError,Set-LABSources

**Comment by bottkars** [comment]
sources will host executables / binaries and installers for various applications intalled in VM´s.
Sources i exposed via hgfs. Since too long pathnames can cause trouble wizth various installers, am early decision was made to limut to 10 Chars.

Might change in future, but is historical when sources was delivered as a vhd
