### ISSUE TITLE
"Invalid configuration file" when creating linked clones

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#21]
Hi, 

getting this message every time labbuildr is creating a linked clone:

```
 ==> Creating Linked Clone E2013N1 from E:\labbuildr\2012R2FallUpdate\2012R2FallUpdate.vmx, VMsize is XL
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
VixDiskLib: Invalid configuration file parameter. Failed to read configuration file.
```

But everything works as it should.

Marcel

**Comment by bottkars** [comment]
the isuuse comes wgen creating the scsi disks. for anothe closed issue i had to uncomment warnings ( https://github.com/bottkars/vmxtoolkit/issues/5 ) iknow the iwarnings are nnoying, and have never been fixed by vmware, as they only appear on some systems. i will pipe the garbage t the errro pipe, so you will no longer see them. closed and moved to vmxtoolkit
